bams_glob: example/*.bam # glob format to find all bams
bams_input: example/{sampleID}.bam # this is the input to the first rule

hg_ref: example/hg.fa
genome_file: example/hg.genome # two column genome file for bedtools
bed_subsets: 100 # how many files the hg reference should be split into
    # this runs VarDict in parallel

vardict: vardict.pl # conda command or path to script
var2vcf: perl var2vcf_valid.pl # not part of conda package? needs to be on path

snpeff_java: java -Xmx2g -jar
snpeff_jar: snpEff.jar
snpeff_config: snpEff.config
snpeff_ref: 'hg' # snpeff database name
